import sqlite3
import json
from datetime import datetime, timedelta
import random

DB_FILE = "pathology.db"

docs = ["Dr. Gregory House", "Dr. Meredith Grey", "Dr. John Dorian", "Dr. Stephen Strange", "Dr. Allison Cameron"]
depts = ["Pulmonology", "Cardiology", "Orthopedics", "Oncology", "General/Primary"]

dummy_patients = [
    {"name": "Arthur Pendelton", "age": 68, "gender": "Male", "bp": "145/90", "temp": "101.4 F", "sym": "Severe dry cough, chest tightness", "phone": "555-010-8432", "email": "arthur.p@autopath.mock", "dis": ["Multifocal Pneumonia"], "sev": "High", "time": 2405, "tr": "Doctor Review"},
    {"name": "Samantha Lewis", "age": 24, "gender": "Female", "bp": "110/70", "temp": "98.6 F", "sym": "Fell off bicycle, wrist pain", "phone": "555-234-9912", "email": "sam.lewis@autopath.mock", "dis": ["Distal Radius Fracture"], "sev": "Medium", "time": 1800, "tr": "Waiting Room"},
    {"name": "David Wallace", "age": 55, "gender": "Male", "bp": "160/100", "temp": "99.1 F", "sym": "Shortness of breath walking up stairs", "phone": "555-943-2211", "email": "d.wallace@autopath.mock", "dis": ["Cardiomegaly", "Pulmonary Edema"], "sev": "Critical", "time": 3200, "tr": "Waiting Room"},
    {"name": "Chloe Vance", "age": 31, "gender": "Female", "bp": "120/80", "temp": "98.4 F", "sym": "Routine physical checkup", "phone": "555-442-9011", "email": "chloe.v@autopath.mock", "dis": [], "sev": "Low", "time": 1205, "tr": "Discharged"},
    {"name": "Marcus Johnson", "age": 42, "gender": "Male", "bp": "135/85", "temp": "100.2 F", "sym": "Persistent productive cough, fatigue", "phone": "555-772-1044", "email": "marcus.j@autopath.mock", "dis": ["Lower Lobe Consolidation"], "sev": "Medium", "time": 2100, "tr": "Doctor Review"},
    {"name": "Eleanor Rigby", "age": 81, "gender": "Female", "bp": "105/65", "temp": "97.8 F", "sym": "Hip pain after slip in bathroom", "phone": "555-882-3301", "email": "erigby@autopath.mock", "dis": ["Femoral Neck Fracture"], "sev": "High", "time": 2850, "tr": "Waiting Room"},
    {"name": "Tyler Durden", "age": 36, "gender": "Male", "bp": "125/82", "temp": "98.9 F", "sym": "Sharp rib pain when breathing deeply", "phone": "555-103-9999", "email": "tdurden@autopath.mock", "dis": ["Rib Contusion", "Minimal Pneumothorax"], "sev": "High", "time": 4100, "tr": "Doctor Review"}
]

conn = sqlite3.connect(DB_FILE)
cursor = conn.cursor()

# Nuke database and rebuild with new Phone/Email schema
cursor.execute('DROP TABLE IF EXISTS patients')
cursor.execute('''
    CREATE TABLE IF NOT EXISTS patients (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        scan_date TEXT,
        patient_name TEXT,
        age INTEGER,
        gender TEXT,
        blood_pressure TEXT,
        temperature TEXT,
        symptoms TEXT,
        referring_doctor TEXT,
        image_name TEXT,
        report_json TEXT,
        requires_followup BOOLEAN,
        processing_time_ms INTEGER,
        department TEXT,
        triage_status TEXT, 
        human_override_note TEXT,
        phone TEXT,
        email TEXT
    )
''')

for p in dummy_patients:
    scan_date = (datetime.now() - timedelta(hours=random.randint(1, 72))).isoformat()
    requires_followup = 1 if p["sev"] in ["High", "Critical"] else 0
    
    mock_report = {
        "clinical_assessment": {
            "diseases": p["dis"],
            "severity": p["sev"],
            "confidence_score": random.randint(85, 99),
            "key_findings": "Mocked technical clinical findings generated by AI seeder script.",
            "differential_diagnosis": "Consider secondary mocked etiology."
        },
        "patient_layman_assessment": {
            "layman_diseases": p["dis"],
            "layman_findings": "Mocked simple findings.",
            "layman_summary": "Mocked patient summary from AI.",
            "treatment_timeline": [{"phase": "Immediate", "action": "Follow medical advice."}]
        },
        "referrals": "Mocked Department Referral."
    }
    
    cursor.execute('''
        INSERT INTO patients (scan_date, patient_name, age, gender, blood_pressure, temperature, symptoms, referring_doctor, image_name, report_json, requires_followup, processing_time_ms, department, triage_status, human_override_note, phone, email)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', (
        scan_date, p["name"], p["age"], p["gender"], p["bp"], p["temp"], p["sym"],
        random.choice(docs), "mock_image.jpg", json.dumps(mock_report),
        requires_followup, p["time"], random.choice(depts), p["tr"], "",
        p["phone"], p["email"]
    ))

conn.commit()
conn.close()
print("7 Realistic Deep-Mock Patients + Phone/Email Contact logic brilliantly seeded!")
